language: ruby
rvm: 
  - 2.1.0
  - 2.2.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: 2.2.3
    - rvm: ruby-head
cache: bundler
sudo: false
before_script:
  - "bundle exec rake db:migrate"
  - "cp config/secrets.yml.sample config/secrets.yml"
script: "bundle exec rspec"
notifications:
  email:
    recipients:
      - rubycorns@googlegroups.com
